language: ruby
bundler_args: "--without development"
before_install:
  - gem install bundler
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx
  - rbx-19mode
  - ree
env:
  - JRUBY_OPTS="-Xcext.enabled=true"
script:
  - gem build xmlhasher.gemspec
  - gem install xmlhasher-*
